class Error:
    ERROR_CODE_DUPLICATED_ITEM = 100
    ERROR_MESSAGE_DUPLICATED_ITEM = "Item was duplicated"
    ERROR_CODE_CREATED_FAILED = 101
    ERROR_MESSAGE_CREATED_FAILED = "Create failed"
    ERROR_CODE_UPDATED_FAILED = 102
    ERROR_MESSAGE_UPDATED_FAILED = "Update failed"
    ERROR_CODE_GOT_FAILED = 103
    ERROR_MESSAGE_GOT_FAILED = "Get failed"
    ERROR_CODE_DELETED_FAILED = 104
    ERROR_MESSAGE_DELETED_FAILED = "Delete failed"
    ERROR_CODE_GOT_EXCEPTION = 105
    ERROR_MESSAGE_GOT_EXCEPTION = 'Get exception'
    ERROR_CODE_GOT_NO_SUCH_ITEM = 106
    ERROR_MESSAGE_GOT_NO_SUCH_ITEM = 'Get no such item'
    ERROR_CODE_INVALID_INPUT_DATA = 107
    ERROR_MESSAGE_INVALID_INPUT_DATA = 'Invalid input data'
